# Dialyzer warnings present in the codebase at the time CI was wired up.
# Each entry is {file, warning_type, line?}. Remove an entry once the
# underlying issue is fixed; the CI Dialyzer job will then catch any
# regression.
#
# These should be triaged and removed over time — they are NOT a permanent
# allowlist. The 2026-05-18 expansion was captured when dialyxir's
# `--format short` crash on OTP 28 was bypassed (commit d8c8ce5), which
# unmasked ~97 pre-existing warnings. Bulk-added so CI can re-block on
# new regressions while incumbent warnings are addressed individually.
[
  # FlowControl: pattern guard against MapSet opaque type
  {"lib/mob_runtime/flow_control.ex", :call, 107},
  {"lib/mob_runtime/flow_control.ex", :call_without_opaque, 107},

  # Router: queue_full branch unreachable given current FlowControl spec
  {"lib/mob_runtime/router.ex", :pattern_match, 465},

  # Existing whole-file warnings (line-agnostic)
  {"lib/mob_noise/session.ex", :unmatched_return},
  {"lib/mob_runtime/discovery.ex", :unmatched_return},
  {"lib/mob_runtime/telemetry.ex", :no_return},
  {"lib/mob_runtime/telemetry.ex", :call},
  {"lib/mob_runtime/topology.ex", :unmatched_return},
  {"lib/mob_store/dedupe.ex", :unmatched_return},
  {"lib/mob_store/relay_cache.ex", :unmatched_return},
  {"lib/mob_store/trust.ex", :call},
  {"lib/mob_routing/tcp.ex", :unmatched_return},
  {"lib/mob_routing/tcp.ex", :pattern_match_cov},

  # Pre-existing warnings in modules not touched by the CubDB migration
  {"lib/mob_runtime/mdns.ex", :call_without_opaque},
  {"lib/mob_routing/udp.ex", :unmatched_return, 253},
  {"lib/mob_routing/udp.ex", :unmatched_return},
  {"lib/mob_routing_ble/port_bridge.ex", :unmatched_return},

  # 2026-05-18 bulk-add (formerly hidden by `--format short` crash on OTP 28).
  # All file-level; line-agnostic so the entries survive minor edits.
  #
  # Dialyzer backlog triage plan (pragmatic, incremental):
  # - Primary pattern: missing @spec/@type on nested structs in the
  #   local_* evidence/audit modules + :unused_fun / :no_return for
  #   intentionally-reachable-only-via-focused-mix-test helpers.
  # - Strategy: do NOT attempt mass @spec on 100+ modules in one go.
  #   Instead, per lab/feature batch:
  #     1. Touch a module in a PR → add 1-3 targeted
  #        `@dialyzer {:nowarn_function, [helper: 3]}` (or :no_return)
  #        right above the offending private fun. This is the source fix.
  #     2. Delete the matching line(s) from this ignore list.
  #   Goal: shrink ignore list by ~10-30 entries per active dev cycle.
  # - Better policy going forward: new modules must pass dialyzer clean
  #   (or carry their own narrow @dialyzer suppressions) before merge.
  # - Tracking: run `mix dialyzer --format short 2>&1 | wc -l` locally vs.
  #   the count of entries here; CI already blocks on *new* warnings
  #   (the ignore is only for the known 375 baseline).
  # - Long-term: when the "local_*" audit scaffolding is no longer
  #   first-class lib code (moved under test/support or generated), many
  #   entries evaporate naturally.
  #
  # Current count: ~375 entries. Target: <200 by end of next release cycle.
  # (See also docs/remaining_items_audit.md and CI job for status.)
  {"lib/mob_node/platform.ex", :call},
  {"lib/mob_node/platform.ex", :no_return},
  {"lib/mob_node/platform.ex", :unused_fun},
  {"lib/mob_node/platform_state.ex", :no_return},
  {"lib/mob_node/ble_self_test.ex", :pattern_match_cov},
  {"lib/mob_node/ble/advert_gossip_scenario.ex", :no_return},
  {"lib/mob_node/ble/advert_gossip_simulator.ex", :no_return},
  {"lib/mob_node/ble/advert_gossip_simulator.ex", :unused_fun},
  {"lib/mob_node/ble/bridge_protocol.ex", :no_return},
  {"lib/mob_node/ble/local_inbox.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_action_summary.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_durable_snapshot.ex", :call},
  {"lib/mob_node/ble/local_inbox_durable_snapshot.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_durable_snapshot.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_persistence_lifecycle.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_persistence_lifecycle.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_persistence_operator.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_persistence_operator.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_persistence_profile.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_persistence_profile.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_presenter.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_product_surface.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_product_surface.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_store.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_store.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_acceptance.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_ux_acceptance.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_decision_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_ux_decision_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_ux_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_ux_operator_capture_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_target_device_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_ux_target_device_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_ux_validation_plan.ex", :unknown_type},
  {"lib/mob_node/ble/local_ios_parity_negative_validation.ex", :unknown_type},
  {"lib/mob_node/ble/local_lifecycle_negative_validation.ex", :unknown_type},
  {"lib/mob_node/ble/local_persistence_acceptance.ex", :no_return},
  {"lib/mob_node/ble/local_persistence_acceptance.ex", :unused_fun},
  {"lib/mob_node/ble/local_persistence_default_decision_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_persistence_default_decision_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_persistence_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_persistence_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_persistence_negative_validation.ex", :unknown_type},
  {"lib/mob_node/ble/local_persistence_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_persistence_operator_capture_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_project_completion_audit.ex", :no_return},
  {"lib/mob_node/ble/local_project_completion_audit.ex", :unused_fun},
  {"lib/mob_node/ble/local_release_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_release_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_release_recent_evidence_inventory.ex", :unknown_type},
  {"lib/mob_node/ble/local_routing_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_routing_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_routing_negative_validation.ex", :unknown_type},
  {"lib/mob_node/ble/local_security_acceptance.ex", :no_return},
  {"lib/mob_node/ble/local_security_acceptance.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_beacon_authentication.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_crypto_negative_validation.ex", :pattern_match_cov},
  {"lib/mob_node/ble/local_security_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_security_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_identity_negative_validation.ex", :unknown_type},
  {"lib/mob_node/ble/local_security_replay_lifecycle_validation.ex", :call},
  {"lib/mob_node/ble/local_security_trust_lifecycle_plan.ex", :no_return},
  {"lib/mob_node/ble/local_security_trust_lifecycle_plan.ex", :unknown_type},
  {"lib/mob_node/ble/local_security_trust_lifecycle_validation.ex", :call},
  {"lib/mob_node/ble/local_security_trust_lifecycle_validation.ex", :no_return},
  {"lib/mob_node/ble/local_security_trust_lifecycle_validation.ex", :unused_fun},
  {"lib/mob_node/ble/message_advertisement.ex", :no_return},
  {"lib/mob_node/ble/message_advertisement.ex", :unused_fun},
  {"lib/mob_node/ble/observability.ex", :unknown_type},
  {"lib/mob_node/ble/peer_table.ex", :pattern_match_cov},
  {"lib/mob_node/home_screen.ex", :no_return},
  {"lib/mob_node/home_screen.ex", :unused_fun},
  # Chat MVP screens — same Mob.Screen handle_event/3 no-return pattern as HomeScreen.
  {"lib/mob_node/chat_screen.ex", :no_return},
  {"lib/mob_node/chat_screen.ex", :unused_fun},
  {"lib/mob_node/channels_screen.ex", :no_return},
  {"lib/mob_node/channels_screen.ex", :unused_fun},
  {"lib/mob_node/session.ex", :no_return},
  {"lib/mob_node/session.ex", :unused_fun},
  {"lib/mob_protocol/codec.ex", :no_return},
  {"lib/mob_protocol/fragment.ex", :no_return},
  {"lib/mob_runtime/discovery.ex", :no_return},
  {"lib/mob_runtime/discovery.ex", :unused_fun},
  {"lib/mob_runtime/mdns.ex", :no_return},
  {"lib/mob_runtime/mdns.ex", :unused_fun},
  {"lib/mob_runtime/router.ex", :call},
  {"lib/mob_runtime/router.ex", :no_return},
  {"lib/mob_runtime/router.ex", :unused_fun},
  {"lib/mob_runtime/session_manager.ex", :unmatched_return},
  {"lib/mob_store/dedupe.ex", :no_return},
  {"lib/mob_routing_ble/bluez_bridge.ex", :call},
  {"lib/mob_routing_ble/bluez_bridge.ex", :no_return},
  {"lib/mob_routing_ble/bluez_bridge.ex", :unused_fun},
  {"lib/mob_routing_ble/port_bridge.ex", :call},
  {"lib/mob_routing_ble/port_bridge.ex", :no_return},
  {"lib/mob_routing/quic.ex", :call},
  {"lib/mob_routing/quic.ex", :no_return},
  {"lib/mob_routing/quic.ex", :unused_fun},
  {"src/mob_node.erl", :call},
  {"src/mob_node.erl", :no_return},

  # 2026-05-18 bulk-add (second pass — Mix.Tasks + remaining lib modules
  # surfaced after the first batch landed).
  {"lib/mob_node/app.ex", :unused_fun},
  {"lib/mob_node/ble/beacon_resolver.ex", :pattern_match},
  {"lib/mob_node/ble/beacon_resolver.ex", :unused_fun},
  {"lib/mob_node/ble/bridge_protocol.ex", :unused_fun},
  {"lib/mob_node/ble/envelope_cache.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_query.ex", :no_return},
  {"lib/mob_node/ble/local_inbox_query.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_resolution.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_resolution.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_canonical_replay_decision.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_canonical_replay_decision.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_crypto_negative_validation.ex", :pattern_match},
  {"lib/mob_runtime/router.ex", :pattern_match_cov},
  {"lib/mob_store/relay_cache.ex", :no_return},
  {"lib/mob_store/trust.ex", :no_return},
  {"lib/mob_routing/tcp.ex", :no_return},
  {"lib/mob_routing/tcp.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.deploy_device.ex", :unknown_function},
  {"lib/mix/tasks/mob.node.deploy_device.ex", :unmatched_return},
  {"lib/mix/tasks/mob.node.local_full_resolution.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_inbox.ux_evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_inbox.ux_evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_inbox.ux_review.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_lifecycle.validation_plan.ex", :pattern_match},
  {"lib/mix/tasks/mob.node.local_multi_hop_hardware.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_persistence.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_persistence.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_persistence.lifecycle_plan.ex", :pattern_match},
  {"lib/mix/tasks/mob.node.local_persistence.production_review.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_release.manifest.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_release.manifest.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_routing.validation_plan.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_security.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_security.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_security.validation_plan.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.remaining_items.audit.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_routing.validation_plan.ex", :pattern_match},
  {"lib/mix/tasks/mob.node.local_security.validation_plan.ex", :pattern_match},

  # 2026-05-18 bulk-add (third pass — additional types per file).
  {"lib/mob_node/ble/local_inbox_persistence_operator.ex", :call},
  {"lib/mob_node/ble/local_persistence_negative_validation.ex", :no_return},
  {"lib/mob_node/ble/local_persistence_negative_validation.ex", :unused_fun},
  {"lib/mob_node/ble/local_routing_decision_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_routing_decision_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_canonical_replay_decision.ex", :call},
  {"lib/mob_node/ble/local_security_canonical_replay_decision.ex", :no_return},
  {"lib/mob_node/ble/local_security_crypto_negative_validation.ex", :no_return},
  {"lib/mob_node/ble/local_security_crypto_negative_validation.ex", :unused_fun},
  {"lib/mob_node/ble/message_advertisement.ex", :pattern_match_cov},
  {"lib/mob_runtime/router.ex", :pattern_match},
  {"lib/mix/tasks/mob.node.capture.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_known_good_transport.review.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_readiness.audit.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_readiness.audit.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_routing.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_routing.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_security.release_review.ex", :unused_fun},

  # 2026-05-18 bulk-add (fourth pass — :invalid_contract, :guard_fail,
  # :contract_with_opaque, :unmatched_return surfaced after dialyxir
  # column-less format was scanned. Final batch.)
  {"lib/mob_node/app.ex", :pattern_match_cov},
  {"lib/mob_node/ble_self_test.ex", :no_return},
  {"lib/mob_node/ble_self_test.ex", :pattern_match},
  {"lib/mob_node/ble_self_test.ex", :unmatched_return},
  {"lib/mob_node/ble_self_test.ex", :unused_fun},
  {"lib/mob_node/ble/advert_only_transport_profile.ex", :contract_with_opaque},
  {"lib/mob_node/ble/local_inbox_durable_snapshot_schema_policy.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_durable_snapshot_schema_policy.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :guard_fail},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :pattern_match_cov},
  {"lib/mob_node/ble/local_inbox_persistence_lifecycle.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_persistence_operator.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_persistence_profile.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_store.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_ux_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_ux_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox.ex", :invalid_contract},
  {"lib/mob_node/ble/local_ios_native_source_inventory.ex", :invalid_contract},
  {"lib/mob_node/ble/local_ios_native_source_inventory.ex", :no_return},
  {"lib/mob_node/ble/local_ios_parity_acceptance.ex", :guard_fail},
  {"lib/mob_node/ble/local_ios_parity_acceptance.ex", :pattern_match},
  {"lib/mob_node/ble/local_ios_parity_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_ios_parity_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_lifecycle_acceptance.ex", :guard_fail},
  {"lib/mob_node/ble/local_lifecycle_acceptance.ex", :pattern_match},
  {"lib/mob_node/ble/local_multi_hop_hardware_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_multi_hop_hardware_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_multi_hop_hardware_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_persistence_acceptance.ex", :invalid_contract},
  {"lib/mob_node/ble/local_persistence_default_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_persistence_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_persistence_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_release_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_routing_acceptance.ex", :guard_fail},
  {"lib/mob_node/ble/local_routing_acceptance.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_acceptance.ex", :guard_fail},
  {"lib/mob_node/ble/local_security_acceptance.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_acceptance.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_beacon_authentication.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_replay_lifecycle_policy.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_trust_lifecycle_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_trust_lifecycle_validation.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_trusted_message_decision.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_trusted_message_decision.ex", :no_return},
  {"lib/mob_node/ble/local_security_trust_model.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :pattern_match_cov},
  {"lib/mob_node/home_screen.ex", :guard_fail},
  {"lib/mob_node/home_screen.ex", :pattern_match_cov},
  {"lib/mob_node/home_screen.ex", :pattern_match},
  {"lib/mob_runtime/flow_control.ex", :invalid_contract},
  {"lib/mob_runtime/flow_control.ex", :no_return},
  {"lib/mob_runtime/flow_control.ex", :unused_fun},
  {"lib/mob_runtime/mdns.ex", :invalid_contract},
  {"lib/mob_runtime/router.ex", :guard_fail},
  {"lib/mob_runtime/outbox.ex", :no_return},
  {"lib/mob_runtime/outbox.ex", :unused_fun},
  {"lib/mob_runtime/session_manager.ex", :no_return},
  {"lib/mob_runtime/topology.ex", :no_return},
  {"lib/mob_store/db.ex", :invalid_contract},
  {"lib/mob_store/dedupe.ex", :invalid_contract},
  {"lib/mob_store/identity.ex", :no_return},
  {"lib/mob_store/identity.ex", :unused_fun},
  {"lib/mob_store/message.ex", :no_return},
  {"lib/mob_store/outbox.ex", :no_return},
  {"lib/mob_store/outbox.ex", :unused_fun},
  {"lib/mob_store/trust.ex", :invalid_contract},
  {"lib/mob_store/trust.ex", :unused_fun},
  {"lib/mob_routing/capabilities.ex", :call},
  {"lib/mob_routing/capabilities.ex", :invalid_contract},
  {"lib/mob_routing/capabilities.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_completion.audit.ex", :pattern_match},
  {"lib/mix/tasks/mob.node.local_inbox.ux_validation_plan.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_ios_parity.evidence.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_multi_hop_hardware.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_multi_hop_hardware.review.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_release.artifact_bundle.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_routing.production_review.ex", :unused_fun},

  # 2026-05-18 bulk-add (fifth pass).
  {"lib/mob_node/ble/local_focused_remaining_items_audit.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_native_surface.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_product_surface.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_ux_acceptance.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_ux_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_persistence_acceptance.ex", :guard_fail},
  {"lib/mob_node/ble/local_persistence_acceptance.ex", :pattern_match},
  {"lib/mob_node/ble/local_routing_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_canonical_replay_decision.ex", :invalid_contract},
  {"lib/mob_node/ble/observability.ex", :invalid_contract},
  {"lib/mob_node/ble/observability.ex", :no_return},
  {"lib/mob_node/ble/observability.ex", :unused_fun},
  {"lib/mob_node/home_screen.ex", :call},
  {"lib/mob_store/identity.ex", :invalid_contract},
  {"lib/mob_routing_ble/bluez_bridge.ex", :invalid_contract},
  {"lib/mob_routing/quic.ex", :invalid_contract},
  {"lib/mix/tasks/mob.node.deploy_device.ex", :no_return},
  {"lib/mix/tasks/mob.node.deploy_device.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_lifecycle.hardware_review.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_lifecycle.validation_plan.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_release.candidate_review.ex", :unused_fun},

  # 2026-05-18 bulk-add (sixth pass).
  {"lib/mob_node/ble/envelope_cache.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_state_copy.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_state_copy.ex", :no_return},
  {"lib/mob_node/ble/local_ios_parity_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_ios_parity_decision_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_ios_parity_decision_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_ios_parity_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_lifecycle_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_lifecycle_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_lifecycle_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_lifecycle_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_lifecycle_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_lifecycle_operator_capture_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_replay_lifecycle_validation.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_replay_lifecycle_validation.ex", :no_return},
  {"lib/mob_node/ble/local_security_replay_lifecycle_validation.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_completion.audit.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_completion.audit.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_ios_parity.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_lifecycle.evidence.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_lifecycle.evidence.ex", :unused_fun},

  # 2026-05-18 bulk-add (seventh pass).
  {"lib/mob_node/ble/beacon_fetch_request.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_fetch_intents.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_ux_target_device_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_ios_parity_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_ios_parity_evidence_manifest.ex", :unused_fun},
  {"lib/mob_protocol/codec.ex", :invalid_contract},
  {"lib/mob_protocol/codec.ex", :pattern_match},
  {"lib/mob_protocol/fragment.ex", :invalid_contract},
  {"lib/mob_protocol/framing.ex", :pattern_match},
  {"lib/mob_runtime/outbox.ex", :pattern_match},
  {"lib/mob_store/message.ex", :invalid_contract},
  {"lib/mob_store/outbox.ex", :invalid_contract},
  {"lib/mob_routing/memory.ex", :no_return},
  {"lib/mob_routing/udp.ex", :pattern_match},
  {"lib/mob_routing/udp.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_ios_parity.hardware_review.ex", :unused_fun},

  # 2026-05-18 bulk-add (eighth pass).
  {"lib/mob_node/ble/local_inbox_action_summary.ex", :invalid_contract},
  {"lib/mob_node/ble/local_inbox_store.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_trust.ex", :invalid_contract},
  {"lib/mob_node/ble/local_routing_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/replay.ex", :invalid_contract},
  {"lib/mob_node/ios_device_build.ex", :call},
  {"lib/mob_node/ios_device_build.ex", :no_return},
  {"lib/mob_node/session.ex", :pattern_match},

  # 2026-05-18 bulk-add (ninth pass).
  {"lib/mob_node/ble/bridge_protocol.ex", :pattern_match},
  {"lib/mob_node/ble/full_envelope_inbox.ex", :pattern_match},
  {"lib/mob_node/ble/full_envelope_inbox.ex", :unused_fun},
  {"lib/mob_node/ble/local_full_message_resolution_evidence_manifest.ex", :invalid_contract},
  {"lib/mob_node/ble/local_full_message_resolution_evidence_manifest.ex", :no_return},
  {"lib/mob_node/ble/local_full_message_resolution_evidence_manifest.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_persistence_policy.ex", :pattern_match},
  {"lib/mob_node/ble/local_inbox_persistence_policy.ex", :unused_fun},
  {"lib/mob_node/ble/local_lifecycle_manual_session.ex", :invalid_contract},
  {"lib/mob_node/ble/local_lifecycle_manual_session.ex", :no_return},
  {"lib/mob_node/ble/local_lifecycle_manual_session.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_authorship_proof.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_beacon_authentication.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_peer_identity_binding.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_replay_protection.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_replay_protection.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_trusted_message_decision.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_trusted_message_decision.ex", :unused_fun},
  {"lib/mob_node/ble/message_advertisement.ex", :pattern_match},
  {"lib/mob_node/ble/message_envelope.ex", :invalid_contract},
  {"lib/mob_node/ble/message_envelope.ex", :no_return},
  {"lib/mob_node/ble/message_envelope.ex", :pattern_match},
  {"lib/mob_node/ble/message_envelope.ex", :unused_fun},
  {"lib/mix/tasks/mob.node.local_full_resolution.evidence.ex", :no_return},

  # 2026-05-18 bulk-add (tenth pass).
  {"lib/mob_node/ble/lifecycle.ex", :invalid_contract},
  {"lib/mob_node/ble/lifecycle.ex", :no_return},
  {"lib/mob_node/ble/local_release_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_release_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_release_operator_capture_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_operator_capture_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_operator_capture_plan.ex", :no_return},
  {"lib/mob_node/ble/local_security_operator_capture_plan.ex", :unused_fun},
  {"lib/mob_node/ble/message_advertisement.ex", :invalid_contract},
  {"lib/mix/tasks/mob.node.local_persistence.lifecycle_plan.ex", :unused_fun},

  # 2026-05-18 bulk-add (eleventh pass).
  {"lib/mob_node/ble/local_security_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_decision_scenario_plan.ex", :no_return},
  {"lib/mix/tasks/mob.node.local_full_resolution.transport_review.ex", :unused_fun},

  # 2026-05-18 bulk-add (twelfth pass).
  {"lib/mob_node/ble/local_lifecycle_decision_scenario_plan.ex", :invalid_contract},
  {"lib/mob_node/ble/local_lifecycle_decision_scenario_plan.ex", :no_return},
  {"lib/mob_node/ble/local_lifecycle_decision_scenario_plan.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_trust_model.ex", :invalid_contract},
  {"lib/mob_runtime/peer_registry.ex", :invalid_contract},

  # 2026-05-18 bulk-add (thirteenth pass).
  {"lib/mob_node/platform.ex", :invalid_contract},
  {"lib/mob_node/ble/advert_gossip_planner.ex", :no_return},
  {"lib/mob_node/ble/beacon_ref.ex", :invalid_contract},
  {"lib/mob_node/ble/beacon_ref.ex", :pattern_match},
  {"lib/mob_node/ble/envelope_cache.ex", :unused_fun},
  {"lib/mob_node/ble/local_security_beacon_reference_risk.ex", :invalid_contract},
  {"lib/mob_node/ble/local_security_beacon_reference_risk.ex", :pattern_match},
  {"lib/mob_node/ble/local_security_beacon_reference_risk.ex", :unused_fun},

  # 2026-05-18 bulk-add (fourteenth pass).
  {"lib/mob_node/ble/advert_gossip_policy.ex", :invalid_contract},
  {"lib/mob_node/ble/advert_gossip_policy.ex", :no_return},
  {"lib/mob_node/ble/advert_gossip_scenario.ex", :invalid_contract},
  {"lib/mob_node/ble/advert_gossip_scenario.ex", :unused_fun},
  {"lib/mob_node/ble/local_inbox_query.ex", :invalid_contract},
  {"lib/mob_node/ble/local_project_completion_audit.ex", :invalid_contract}
]
