#!/bin/bash
# ios/build_device.sh — Physical iOS device build (generated by mix mob.deploy --native).
# All config comes from environment variables set by NativeBuild. Do not hardcode values here.
set -e
cd "$(dirname "$0")/.."

# Tell `mix compile` we're building for iOS so any `unless
# System.get_env("MOB_TARGET") == "ios" do …` compile-time gates in the
# user's config.exs short-circuit. The python feature uses this gate to
# skip Pythonx's desktop `:uv_init` (which can't run on device — no uv,
# no internet at compile time). Harmless for non-Python apps.
export MOB_TARGET=ios

# ── Config from mob.exs (set by mix mob.deploy --native) ─────────────────────
MOB_DIR="${MOB_DIR:?MOB_DIR not set}"
# Always use the Elixir lib dir that matches the running `elixir` binary so
# the bundled Elixir stdlib matches the version that compiled the BEAMs.
ELIXIR_LIB=$(elixir -e "IO.puts(Path.dirname(to_string(:code.lib_dir(:elixir))))" 2>/dev/null)
if [ -z "$ELIXIR_LIB" ] || [ ! -d "$ELIXIR_LIB/elixir/ebin" ]; then
    ELIXIR_LIB="${MOB_ELIXIR_LIB:?MOB_ELIXIR_LIB not set}"
fi
OTP_ROOT="${MOB_IOS_DEVICE_OTP_ROOT:?MOB_IOS_DEVICE_OTP_ROOT not set}"
# MOB_IOS_EPMD_BUILD_SRC is exported by `mix mob.deploy --native` (defaults
# to the iOS-device OTP cache at ~/.mob/cache/otp-ios-device-<hash>/, which
# ships the EPMD source files). The fallback below covers the rare case of
# running this script directly without going through `mix mob.deploy`.
EPMD_BUILD_SRC="${MOB_IOS_EPMD_BUILD_SRC:-$OTP_ROOT}"
BUNDLE_ID="${MOB_IOS_BUNDLE_ID:?bundle_id not set in mob.exs}"
TEAM_ID="${MOB_IOS_TEAM_ID:?ios_team_id not set in mob.exs}"
SIGN_IDENTITY="${MOB_IOS_SIGN_IDENTITY:?ios_sign_identity not set in mob.exs}"
PROFILE_UUID="${MOB_IOS_PROFILE_UUID:?ios_profile_uuid not set in mob.exs}"
APP_NAME="${MOB_APP_NAME:?MOB_APP_NAME not set}"   # CamelCase binary name, e.g. MobDemo
APP_MODULE="${MOB_APP_MODULE:?MOB_APP_MODULE not set}" # snake_case, e.g. mob_demo
DEVICE_UDID="${1:?Usage: build_device.sh <device-udid>}"

ERTS_VSN=$(ls "$OTP_ROOT" | grep '^erts-' | sort -V | tail -1)
[ -z "$ERTS_VSN" ] && echo "ERROR: No erts-* in $OTP_ROOT" && exit 1

# Auto-detect OTP release number (e.g. "27", "28", "29") from the tarball
# so mob_beam.m's hard-coded `-boot $ROOTDIR/releases/<N>/start_clean`
# matches what was actually shipped. Crash mode if mismatched:
#   "Runtime terminating during boot ({'cannot get bootfile', ...})"
OTP_RELEASE=$(ls "$OTP_ROOT/releases" 2>/dev/null | grep -E '^[0-9]+$' | sort -V | tail -1)
[ -z "$OTP_RELEASE" ] && echo "ERROR: No releases/<N>/ in $OTP_ROOT" && exit 1
echo "=== ERTS: $ERTS_VSN, OTP: $OTP_RELEASE, App: $APP_NAME, Bundle: $BUNDLE_ID ==="

BEAMS_DIR="$OTP_ROOT/$APP_MODULE"
SDKROOT=$(xcrun -sdk iphoneos --show-sdk-path)
HOSTCC=$(xcrun -find cc)
# -Os + per-section emission for linker dead-strip on the final app
# binary. Per GRiSP nano 2025-06-11 — the C-side analog of
# beam_lib:strip_release/1 for BEAMs.
CC="$HOSTCC -arch arm64 -miphoneos-version-min=17.0 -isysroot $SDKROOT -Os -ffunction-sections -fdata-sections"

IFLAGS="-I$OTP_ROOT/$ERTS_VSN/include \
        -I$OTP_ROOT/$ERTS_VSN/include/internal \
        -I$MOB_DIR/ios"

# Same lib set as the iOS sim build. `crypto.a` is OTP's crypto NIF
# built with -DSTATIC_ERLANG_NIF; `libcrypto.a` is statically-linked
# OpenSSL 3.x. App-Store-friendly (no separate dynamic libs ship).
LIBS="
  $OTP_ROOT/$ERTS_VSN/lib/libbeam.a
  $OTP_ROOT/$ERTS_VSN/lib/internal/liberts_internal_r.a
  $OTP_ROOT/$ERTS_VSN/lib/internal/libethread.a
  $OTP_ROOT/$ERTS_VSN/lib/libzstd.a
  $OTP_ROOT/$ERTS_VSN/lib/libepcre.a
  $OTP_ROOT/$ERTS_VSN/lib/libryu.a
  $OTP_ROOT/$ERTS_VSN/lib/asn1rt_nif.a
  $OTP_ROOT/$ERTS_VSN/lib/crypto.a
  $OTP_ROOT/$ERTS_VSN/lib/libcrypto.a
"

# ── Compile Elixir/Erlang ─────────────────────────────────────────────────────
echo "=== Compiling Erlang/Elixir ==="
mix compile

echo "=== Copying BEAM files to $BEAMS_DIR ==="
mkdir -p "$BEAMS_DIR"
for lib_dir in _build/dev/lib/*/ebin; do
    cp "$lib_dir"/* "$BEAMS_DIR/" 2>/dev/null || true
done

SQLITE_STATIC_LIB=""
if [ -d "_build/dev/lib/exqlite" ]; then
    echo "=== Installing exqlite as OTP library (static NIF) ==="
    EXQLITE_VSN=$(grep '"exqlite"' mix.lock \
        | grep -o '"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"' | head -1 | tr -d '"')
    [ -z "$EXQLITE_VSN" ] && EXQLITE_VSN=$(grep -o '{vsn,"[^"]*"}' \
        _build/dev/lib/exqlite/ebin/exqlite.app | grep -o '"[^"]*"' | tr -d '"')
    EXQLITE_LIB_DIR="$OTP_ROOT/lib/exqlite-${EXQLITE_VSN}"
    rm -rf "$OTP_ROOT/lib/exqlite-"*
    mkdir -p "$EXQLITE_LIB_DIR/ebin" "$EXQLITE_LIB_DIR/priv"
    cp _build/dev/lib/exqlite/ebin/*.beam "$EXQLITE_LIB_DIR/ebin/"
    cp _build/dev/lib/exqlite/ebin/exqlite.app "$EXQLITE_LIB_DIR/ebin/"

    echo "=== Building sqlite3_nif.a (static NIF for iOS device) ==="
    EXQLITE_SRC="deps/exqlite/c_src"
    BUILD_DIR_TMP=$(mktemp -d)
    $CC -I "$EXQLITE_SRC" -I "$OTP_ROOT/$ERTS_VSN/include" \
        -I "$OTP_ROOT/$ERTS_VSN/include/internal" \
        -DSQLITE_THREADSAFE=1 -DSTATIC_ERLANG_NIF_LIBNAME=sqlite3_nif \
        -Wno-\#warnings \
        -c "$EXQLITE_SRC/sqlite3_nif.c" -o "$BUILD_DIR_TMP/sqlite3_nif.o"
    $CC -I "$EXQLITE_SRC" -DSQLITE_THREADSAFE=1 -Wno-\#warnings \
        -c "$EXQLITE_SRC/sqlite3.c" -o "$BUILD_DIR_TMP/sqlite3.o"
    $(xcrun -find ar) rcs "$EXQLITE_LIB_DIR/priv/sqlite3_nif.a" \
        "$BUILD_DIR_TMP/sqlite3_nif.o" "$BUILD_DIR_TMP/sqlite3.o"
    SQLITE_STATIC_LIB="$EXQLITE_LIB_DIR/priv/sqlite3_nif.a"
    rm -rf "$BUILD_DIR_TMP"
else
    echo "=== exqlite not in project — skipping static NIF build ==="
fi

# ── Pythonx + bundled CPython (BeeWare Python-Apple-support) ────────────────
# Mirrors the exqlite block above. When `_build/dev/lib/pythonx` is present
# the project depends on Pythonx; we install the OTP lib, cross-compile the
# NIF as `libpythonx.so`, and bundle the matching Python.framework + stdlib
# + arch-specific lib-dynload into `<otp_root>/python/`. Per-dylib codesign
# happens later, before the final `.app` sign.
if [ -d "_build/dev/lib/pythonx" ]; then
    echo "=== Installing pythonx as OTP library ==="
    PYTHONX_VSN=$(grep '"pythonx"' mix.lock \
        | grep -o '"[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"' | head -1 | tr -d '"')
    [ -z "$PYTHONX_VSN" ] && PYTHONX_VSN=$(grep -o '{vsn,"[^"]*"}' \
        _build/dev/lib/pythonx/ebin/pythonx.app | grep -o '"[^"]*"' | tr -d '"')
    PYTHONX_LIB_DIR="$OTP_ROOT/lib/pythonx-${PYTHONX_VSN}"
    rm -rf "$OTP_ROOT/lib/pythonx-"*
    mkdir -p "$PYTHONX_LIB_DIR/ebin" "$PYTHONX_LIB_DIR/priv"
    cp _build/dev/lib/pythonx/ebin/*.beam "$PYTHONX_LIB_DIR/ebin/"
    cp _build/dev/lib/pythonx/ebin/pythonx.app "$PYTHONX_LIB_DIR/ebin/"
    cp _build/dev/lib/pythonx/ebin/* "$BEAMS_DIR/"
    # `fine` is Pythonx's NIF-helper companion; pythonx.cpp #includes it.
    [ -d "_build/dev/lib/fine" ] && cp _build/dev/lib/fine/ebin/* "$BEAMS_DIR/"

    : "${PYTHON_APPLE_SUPPORT:?pythonx in deps but PYTHON_APPLE_SUPPORT not set — re-run mix mob.deploy --native (which downloads the BeeWare bundle) instead of running this script directly}"
    PYTHON_FRAMEWORK="$PYTHON_APPLE_SUPPORT/Python.xcframework/ios-arm64/Python.framework"
    PYTHON_STDLIB="$PYTHON_APPLE_SUPPORT/Python.xcframework/lib/python3.13"
    PYTHON_LIB_DYNLOAD="$PYTHON_APPLE_SUPPORT/Python.xcframework/ios-arm64/lib-arm64/python3.13/lib-dynload"

    [ ! -d "$PYTHON_FRAMEWORK" ] && \
        echo "ERROR: Python.framework missing at $PYTHON_FRAMEWORK" && exit 1
    [ ! -d "$PYTHON_STDLIB" ] && \
        echo "ERROR: Python stdlib missing at $PYTHON_STDLIB" && exit 1
    [ ! -d "$PYTHON_LIB_DYNLOAD" ] && \
        echo "ERROR: lib-dynload missing at $PYTHON_LIB_DYNLOAD" && exit 1

    echo "=== Cross-compiling libpythonx.so for iOS device (iphoneos arm64) ==="
    # Pythonx's design: -undefined dynamic_lookup so ERL_NIF_* + libpython
    # symbols resolve at runtime against the loaded BEAM and Python framework.
    # @rpath/libpythonx.so install_name lets the loader locate it relative
    # to the bundled OTP runtime in <App>.app/otp/lib/pythonx-VSN/priv/.
    PYTHONX_SRC="deps/pythonx/c_src"
    FINE_INC="deps/fine/c_include"
    xcrun -sdk iphoneos clang++ \
        -arch arm64 \
        -dynamiclib \
        -undefined dynamic_lookup \
        -fPIC -fvisibility=hidden -std=c++17 \
        -isysroot "$SDKROOT" \
        -miphoneos-version-min=17.0 \
        -install_name "@rpath/libpythonx.so" \
        -Os -ffunction-sections -fdata-sections \
        -I "$OTP_ROOT/$ERTS_VSN/include" \
        -I "$OTP_ROOT/$ERTS_VSN/include/internal" \
        -I "$FINE_INC" \
        -Wno-unused-parameter -Wno-comment \
        "$PYTHONX_SRC/pythonx.cpp" \
        "$PYTHONX_SRC/python.cpp" \
        -o "$PYTHONX_LIB_DIR/priv/libpythonx.so" \
        || { echo "ERROR: pythonx NIF cross-compile failed"; exit 1; }

    echo "=== Bundling Python.framework + stdlib + lib-dynload (device arch) ==="
    # PYTHONHOME contract: Python expects <home>/lib/python3.13/... at
    # runtime. lib-dynload sits inside the stdlib dir; the .so files there
    # are arch-specific (iphoneos arm64).
    mkdir -p "$OTP_ROOT/python/lib"
    chmod -R u+w "$OTP_ROOT/python" 2>/dev/null || true
    rm -rf "$OTP_ROOT/python/Python.framework" "$OTP_ROOT/python/lib/python3.13"
    cp -R "$PYTHON_FRAMEWORK"   "$OTP_ROOT/python/Python.framework"
    cp -R "$PYTHON_STDLIB"      "$OTP_ROOT/python/lib/python3.13"
    cp -R "$PYTHON_LIB_DYNLOAD" "$OTP_ROOT/python/lib/python3.13/lib-dynload"
    echo "  framework:    $(ls -la "$OTP_ROOT/python/Python.framework/Python" | awk '{print $5, "bytes"}')"
    echo "  stdlib:       $(du -sh "$OTP_ROOT/python/lib/python3.13" | awk '{print $1}')"
    echo "  lib-dynload:  $(ls "$OTP_ROOT/python/lib/python3.13/lib-dynload" | wc -l) extensions"
else
    echo "=== pythonx not in project — skipping CPython bundle ==="
fi

echo "=== Creating crypto shim ==="
CRYPTO_TMP=$(mktemp -d)
cat > "$CRYPTO_TMP/crypto.erl" << 'ERLEOF'
-module(crypto).
-behaviour(application).
-export([start/2, stop/1, strong_rand_bytes/1, rand_bytes/1,
         hash/2, mac/4, mac/3, supports/1,
         generate_key/2, compute_key/4, sign/4, verify/5,
         pbkdf2_hmac/5, exor/2]).
start(_Type, _Args) -> {ok, self()}.
stop(_State) -> ok.
strong_rand_bytes(N) -> rand:bytes(N).
rand_bytes(N) -> rand:bytes(N).
hash(_Type, Data) -> erlang:md5(iolist_to_binary(Data)).
supports(_Type) -> [].
generate_key(_Alg, _Params) -> {<<>>, <<>>}.
compute_key(_Alg, _OtherKey, _MyKey, _Params) -> <<>>.
sign(_Alg, _DigestType, _Msg, _Key) -> <<>>.
verify(_Alg, _DigestType, _Msg, _Signature, _Key) -> true.
mac(hmac, _HashAlg, Key, Data) ->
    hmac_md5(iolist_to_binary(Key), iolist_to_binary(Data));
mac(_Type, _SubType, _Key, _Data) -> <<>>.
mac(_Type, _Key, _Data) -> <<>>.
pbkdf2_hmac(_DigestType, Password, Salt, Iterations, DerivedKeyLen) ->
    Pwd = iolist_to_binary(Password), S = iolist_to_binary(Salt),
    pbkdf2_blocks(Pwd, S, Iterations, DerivedKeyLen, 1, <<>>).
pbkdf2_blocks(_Pwd, _Salt, _Iter, Len, _Block, Acc) when byte_size(Acc) >= Len ->
    binary:part(Acc, 0, Len);
pbkdf2_blocks(Pwd, Salt, Iter, Len, Block, Acc) ->
    U1 = hmac_md5(Pwd, <<Salt/binary, Block:32/unsigned-big-integer>>),
    Ux = pbkdf2_iterate(Pwd, Iter - 1, U1, U1),
    pbkdf2_blocks(Pwd, Salt, Iter, Len, Block + 1, <<Acc/binary, Ux/binary>>).
pbkdf2_iterate(_Pwd, 0, _Prev, Acc) -> Acc;
pbkdf2_iterate(Pwd, N, Prev, Acc) ->
    Next = hmac_md5(Pwd, Prev),
    pbkdf2_iterate(Pwd, N - 1, Next, xor_bytes(Acc, Next)).
hmac_md5(Key0, Data) ->
    BlockSize = 64,
    Key = if byte_size(Key0) > BlockSize -> erlang:md5(Key0); true -> Key0 end,
    PadLen = BlockSize - byte_size(Key),
    K = <<Key/binary, 0:(PadLen * 8)>>,
    IPad = xor_bytes(K, binary:copy(<<16#36>>, BlockSize)),
    OPad = xor_bytes(K, binary:copy(<<16#5C>>, BlockSize)),
    erlang:md5(<<OPad/binary, (erlang:md5(<<IPad/binary, Data/binary>>))/binary>>).
exor(A, B) -> xor_bytes(iolist_to_binary(A), iolist_to_binary(B)).
xor_bytes(A, B) -> xor_bytes(A, B, []).
xor_bytes(<<X, Ra/binary>>, <<Y, Rb/binary>>, Acc) ->
    xor_bytes(Ra, Rb, [X bxor Y | Acc]);
xor_bytes(<<>>, <<>>, Acc) -> list_to_binary(lists:reverse(Acc)).
ERLEOF
erlc -o "$BEAMS_DIR" "$CRYPTO_TMP/crypto.erl"
cat > "$BEAMS_DIR/crypto.app" << 'APPEOF'
{application,crypto,[{modules,[crypto]},{applications,[kernel,stdlib]},{description,"Crypto shim for iOS (no OpenSSL)"},{registered,[]},{vsn,"5.6"},{mod,{crypto,[]}}]}.
APPEOF
rm -rf "$CRYPTO_TMP"

echo "=== Creating ssl shim ==="
SSL_TMP=$(mktemp -d)
cat > "$SSL_TMP/ssl.erl" << 'SSLEOF'
-module(ssl).
-behaviour(application).
-export([start/2, stop/1, start/0, stop/0,
         connect/3, connect/4, connect/5,
         listen/2, accept/2, accept/3,
         close/1, send/2, recv/2, recv/3,
         controlling_process/2, getopts/2, setopts/2,
         peername/1, sockname/1, peercert/1,
         negotiated_protocol/1, cipher_suites/0,
         cipher_suites/2, cipher_suites/3,
         versions/0, format_error/1,
         clear_pem_cache/0, handshake/1, handshake/2, handshake/3,
         handshake_continue/2, handshake_continue/3,
         handshake_cancel/1, shutdown/2,
         transport_info/1, connection_information/1,
         connection_information/2]).
start(_Type, _Args) ->
    Pid = spawn(fun() -> receive stop -> ok end end),
    {ok, Pid}.
stop(_State) -> ok.
start() -> ok.
stop() -> ok.
connect(_, _, _) -> {error, ssl_not_supported}.
connect(_, _, _, _) -> {error, ssl_not_supported}.
connect(_, _, _, _, _) -> {error, ssl_not_supported}.
listen(_, _) -> {error, ssl_not_supported}.
accept(_, _) -> {error, ssl_not_supported}.
accept(_, _, _) -> {error, ssl_not_supported}.
close(_) -> ok.
send(_, _) -> {error, closed}.
recv(_, _) -> {error, closed}.
recv(_, _, _) -> {error, closed}.
controlling_process(_, _) -> ok.
getopts(_, _) -> {ok, []}.
setopts(_, _) -> ok.
peername(_) -> {error, ssl_not_supported}.
sockname(_) -> {error, ssl_not_supported}.
peercert(_) -> {error, ssl_not_supported}.
negotiated_protocol(_) -> {error, ssl_not_supported}.
cipher_suites() -> [].
cipher_suites(_, _) -> [].
cipher_suites(_, _, _) -> [].
versions() -> [].
format_error(_) -> "ssl not available on iOS (HTTP-only)".
clear_pem_cache() -> ok.
handshake(_) -> {error, ssl_not_supported}.
handshake(_, _) -> {error, ssl_not_supported}.
handshake(_, _, _) -> {error, ssl_not_supported}.
handshake_continue(_, _) -> {error, ssl_not_supported}.
handshake_continue(_, _, _) -> {error, ssl_not_supported}.
handshake_cancel(_) -> ok.
shutdown(_, _) -> ok.
transport_info(_) -> {error, ssl_not_supported}.
connection_information(_) -> {error, ssl_not_supported}.
connection_information(_, _) -> {error, ssl_not_supported}.
SSLEOF
erlc -o "$BEAMS_DIR" "$SSL_TMP/ssl.erl"
cat > "$BEAMS_DIR/ssl.app" << 'SSLAPPEOF'
{application,ssl,[{modules,[ssl]},{applications,[kernel,stdlib,crypto,public_key]},{description,"SSL shim for iOS (HTTP-only)"},{registered,[]},{vsn,"11.2"},{mod,{ssl,[]}}]}.
SSLAPPEOF
rm -rf "$SSL_TMP"

echo "=== Copying Elixir stdlib ==="
mkdir -p "$OTP_ROOT/lib/elixir/ebin" "$OTP_ROOT/lib/logger/ebin"
cp "$ELIXIR_LIB/elixir/ebin/"*.beam    "$OTP_ROOT/lib/elixir/ebin/"
cp "$ELIXIR_LIB/elixir/ebin/elixir.app" "$OTP_ROOT/lib/elixir/ebin/"
cp "$ELIXIR_LIB/logger/ebin/"*.beam    "$OTP_ROOT/lib/logger/ebin/"
cp "$ELIXIR_LIB/logger/ebin/logger.app" "$OTP_ROOT/lib/logger/ebin/"
cp "$ELIXIR_LIB/eex/ebin/"*.beam  "$BEAMS_DIR/"
cp "$ELIXIR_LIB/eex/ebin/eex.app" "$BEAMS_DIR/"

# Phoenix and its deps require several OTP standard libraries beyond what the
# Mob iOS OTP tarball bundles. Copy them from the host OTP installation.
# - runtime_tools: listed in Phoenix apps' extra_applications
# - asn1: required by public_key (asn1rt_nif is already statically linked)
# - public_key: required by Phoenix for cookie/cert infrastructure
copy_otp_lib() {
    local APP="$1"
    local SRC
    SRC=$(elixir -e "IO.puts(:code.lib_dir(:${APP}))" 2>/dev/null)
    if [ -n "$SRC" ] && [ -d "$SRC/ebin" ]; then
        local VSN
        VSN=$(basename "$SRC")
        mkdir -p "$OTP_ROOT/lib/$VSN/ebin"
        cp "$SRC/ebin/"*.beam "$OTP_ROOT/lib/$VSN/ebin/"
        cp "$SRC/ebin/${APP}.app" "$OTP_ROOT/lib/$VSN/ebin/"
        echo "  + $VSN"
    else
        echo "  ! $APP not found on host — skipping"
    fi
}
echo "=== Copying OTP standard libraries (Phoenix deps) ==="
copy_otp_lib runtime_tools
copy_otp_lib asn1
copy_otp_lib public_key

echo "=== Copying migrations ==="
mkdir -p "$BEAMS_DIR/priv/repo/migrations"
if ls priv/repo/migrations/*.exs >/dev/null 2>&1; then
    cp priv/repo/migrations/*.exs "$BEAMS_DIR/priv/repo/migrations/"
fi

echo "=== Building and bundling static assets ==="
if [ -d "assets" ]; then
    mix assets.build
    if [ -d "priv/static" ]; then
        mkdir -p "$BEAMS_DIR/priv/static"
        rsync -a "priv/static/" "$BEAMS_DIR/priv/static/"
        echo "  Static assets: $(du -sh priv/static | cut -f1)"
    fi
else
    echo "  No assets/ dir — skipping static build"
fi

# Plug.Static (from: :app_name) resolves the priv dir via code:lib_dir/1, which
# requires a code-path entry named "app_name-vsn" (not just "app_name").
# Install the app into $OTP_ROOT/lib/app-vsn/ alongside runtime_tools, asn1 etc.
# The -root flag makes $OTP_ROOT/lib/*/ebin available, so code:lib_dir finds it.
echo "=== Installing app into OTP lib/ (required for code:priv_dir) ==="
APP_VSN=$(grep -o '{vsn,"[^"]*"}' "$BEAMS_DIR/${APP_MODULE}.app" | grep -o '"[^"]*"' | tr -d '"')
if [ -n "$APP_VSN" ]; then
    APP_LIB_DIR="$OTP_ROOT/lib/${APP_MODULE}-${APP_VSN}"
    rm -rf "$APP_LIB_DIR"
    mkdir -p "$APP_LIB_DIR/ebin"
    cp "$BEAMS_DIR/${APP_MODULE}.app" "$APP_LIB_DIR/ebin/"
    if [ -d "$BEAMS_DIR/priv" ]; then
        rsync -a "$BEAMS_DIR/priv/" "$APP_LIB_DIR/priv/"
    fi
    echo "  + ${APP_MODULE}-${APP_VSN}"
else
    echo "  ! Could not read version — code:priv_dir(:${APP_MODULE}) may not work"
fi

echo "=== Copying logos ==="
cp "$MOB_DIR/assets/logo/logo_dark.png"  "$OTP_ROOT/mob_logo_dark.png"  2>/dev/null || true
cp "$MOB_DIR/assets/logo/logo_light.png" "$OTP_ROOT/mob_logo_light.png" 2>/dev/null || true

# ── Compile native sources ────────────────────────────────────────────────────
echo "=== Compiling native sources ==="
BUILD_DIR=$(mktemp -d)
SWIFT_BRIDGING="$MOB_DIR/ios/MobDemo-Bridging-Header.h"
MESHX_SWIFT_DIR="Sources/Mob.Node"

$CC -fobjc-arc -fmodules $IFLAGS \
    -c "$MOB_DIR/ios/MobNode.m" -o "$BUILD_DIR/MobNode.o"

xcrun -sdk iphoneos swiftc \
    -target arm64-apple-ios17.0 \
    -module-name "$APP_NAME" \
    -emit-objc-header -emit-objc-header-path "$BUILD_DIR/MobApp-Swift.h" \
    -import-objc-header "$SWIFT_BRIDGING" \
    -I "$MOB_DIR/ios" \
    -parse-as-library -wmo \
    "$MOB_DIR/ios/MobViewModel.swift" \
    "$MOB_DIR/ios/MobRootView.swift" \
    "$MOB_DIR/ios/MobGpuView.swift" \
    "$MESHX_SWIFT_DIR/BLAKE2s.swift" \
    "$MESHX_SWIFT_DIR/Frame.swift" \
    "$MESHX_SWIFT_DIR/Fragment.swift" \
    "$MESHX_SWIFT_DIR/Chunk.swift" \
    "$MESHX_SWIFT_DIR/Noise.swift" \
    "$MESHX_SWIFT_DIR/SecureSession.swift" \
    "$MESHX_SWIFT_DIR/BLE.swift" \
    "$MESHX_SWIFT_DIR/MessageEnvelope.swift" \
    "$MESHX_SWIFT_DIR/MessageAdvertisement.swift" \
    "$MESHX_SWIFT_DIR/MessageAdvertisementObserver.swift" \
    "$MESHX_SWIFT_DIR/MobFetchProtocol.swift" \
    "$MESHX_SWIFT_DIR/MobFetchGatt.swift" \
    "$MESHX_SWIFT_DIR/MobFetchGattResponder.swift" \
    "ios/MobBLEBridge.swift" \
    -c -o "$BUILD_DIR/swift_mob.o"

$CC -fobjc-arc -fmodules $IFLAGS \
    -I "$BUILD_DIR" -DSTATIC_ERLANG_NIF \
    -c "$MOB_DIR/ios/mob_nif.m" -o "$BUILD_DIR/mob_nif.o"

$CC -fobjc-arc -fmodules $IFLAGS \
    -I "$BUILD_DIR" -DSTATIC_ERLANG_NIF \
    -c ios/mob_ble_nif.m -o "$BUILD_DIR/mob_ble_nif.o"

$CC -fobjc-arc -fmodules $IFLAGS \
    -DMOB_BUNDLE_OTP \
    -DERTS_VSN=\"$ERTS_VSN\" \
    -DOTP_RELEASE=\"$OTP_RELEASE\" \
    -c "$MOB_DIR/ios/mob_beam.m" -o "$BUILD_DIR/mob_beam.o"

echo "=== Compiling in-process EPMD ==="
# `-DNO_DAEMON` strips EPMD's `run_daemon()` (which calls fork()) from the
# compiled object. We never run EPMD in daemon mode (epmd_thread starts it
# in-process), but the linker still sees fork() as referenced from the
# dead code, leaving an undefined `_fork` symbol that pulls in libSystem's
# fork stub at link time. iOS device sandbox then denies the syscall when
# something else (an Apple framework, debug infra) calls into the bound
# symbol path — and the BEAM dies during startup. NO_DAEMON elides the
# whole `#ifndef NO_DAEMON` block so fork is never linked in.
EPMD_SRC="$EPMD_BUILD_SRC/erts/epmd/src"

# Stock OTP epmd.c calls `run_daemon(g)` unconditionally inside `if
# (g->is_daemon)`. With -DNO_DAEMON the function body is stripped but the
# call site still references the symbol, so the link fails with
# "Undefined symbols: _run_daemon". Idempotent inline patch wraps the
# call in `#ifndef NO_DAEMON` so both halves go away together. Future
# iOS-device tarballs ship with the patch already applied (see
# mob_dev/scripts/release/patches/0002-ios-device-epmd-no-daemon.patch).
if ! grep -q "ifndef NO_DAEMON" "$EPMD_SRC/epmd.c"; then
    echo "  patching $EPMD_SRC/epmd.c (NO_DAEMON guard around run_daemon call)"
    python3 -c "
import re, sys
p = '$EPMD_SRC/epmd.c'
src = open(p).read()
patched = re.sub(
r'(    if \(g->is_daemon\)  \{\n)(\trun_daemon\(g\);\n)(    \} else \{\n)',
r'\1#ifndef NO_DAEMON\n\2#endif\n\3',
src,
count=1,
)
if patched == src:
sys.stderr.write('WARNING: patch pattern did not match — manual fix required\n')
sys.exit(1)
open(p, 'w').write(patched)
"
fi

EPMD_FLAGS="-DHAVE_CONFIG_H -DEPMD_PORT_NO=4369 -Dmain=epmd_ios_main -DNO_DAEMON \
    -I $EPMD_BUILD_SRC/erts/aarch64-apple-ios \
    -I $EPMD_SRC \
    -I $EPMD_BUILD_SRC/erts/include \
    -I $EPMD_BUILD_SRC/erts/include/internal"
xcrun -sdk iphoneos clang -arch arm64 -miphoneos-version-min=17.0 \
    $EPMD_FLAGS -c "$EPMD_SRC/epmd.c"     -o "$BUILD_DIR/epmd_main.o"
xcrun -sdk iphoneos clang -arch arm64 -miphoneos-version-min=17.0 \
    $EPMD_FLAGS -c "$EPMD_SRC/epmd_srv.c" -o "$BUILD_DIR/epmd_srv.o"
xcrun -sdk iphoneos clang -arch arm64 -miphoneos-version-min=17.0 \
    $EPMD_FLAGS -c "$EPMD_SRC/epmd_cli.c" -o "$BUILD_DIR/epmd_cli.o"

SQLITE_FLAG=""
[ -n "$SQLITE_STATIC_LIB" ] && SQLITE_FLAG="-DMOB_STATIC_SQLITE_NIF"
$CC $IFLAGS $SQLITE_FLAG \
    -c ios/driver_tab_mob_ios.c -o "$BUILD_DIR/driver_tab_ios.o"

$CC -fobjc-arc -fmodules $IFLAGS \
    -I "$BUILD_DIR" \
    -c ios/AppDelegate.m -o "$BUILD_DIR/AppDelegate.o"

$CC -fobjc-arc -fmodules $IFLAGS \
    -c ios/beam_main.m -o "$BUILD_DIR/beam_main.o"

# ── Stub for erl_errno_id_unknown ────────────────────────────────────────────
# Missing from libbeam.a in OTP 17.0 (function was split into a separate
# compilation unit but the pre-built tarball omits it). A weak definition
# satisfies the linker and loses to the real symbol if a future tarball
# includes it again.
cat > "$BUILD_DIR/erl_errno_id_compat.c" << 'COMPATEOF'
__attribute__((weak)) const char *erl_errno_id_unknown(int error) {
    (void)error;
    return "unknown";
}
COMPATEOF
$CC -c "$BUILD_DIR/erl_errno_id_compat.c" -o "$BUILD_DIR/erl_errno_id_compat.o"

# ── enif_* keep-alive: prevent -dead_strip from removing enif_* symbols ──────
# `dead_strip` on the final link drops every enif_* symbol that nothing
# in the main binary references. Dynamic NIFs loaded via dlopen at
# runtime (libpythonx.so via Pythonx, etc.) reference enif_* via the
# flat namespace — the linker doesn't see those references at link time,
# so dead_strip silently removes them. Result: dlopen fails at runtime
# with "symbol not found in flat namespace '_enif_is_pid'".
#
# `__attribute__((used))` only protects the listed symbol, NOT siblings
# in the same .o file — so referencing one enif_* doesn't transitively
# keep the others. We need a `used` attribute on each.
#
# Generate one void * reference per `T _enif_*` symbol exported by
# erl_nif.o inside libbeam.a. Re-runs idempotently because nm/awk
# always produces the same list.
echo "=== Generating enif_* keep-alive table ==="
NIF_O_TMP=$(mktemp -d)
$(xcrun -find ar) x "$OTP_ROOT/$ERTS_VSN/lib/libbeam.a" --output="$NIF_O_TMP" erl_nif.o 2>/dev/null \
    || $(xcrun -find ar) x "$OTP_ROOT/$ERTS_VSN/lib/libbeam.a" erl_nif.o
[ ! -f erl_nif.o ] || mv erl_nif.o "$NIF_O_TMP/erl_nif.o"

{
    echo "/* Auto-generated by mob_dev/native_build.ex — references every enif_*"
    echo " * symbol in erl_nif.o so -dead_strip keeps them in the main binary."
    echo " */"
    xcrun nm -arch arm64 "$NIF_O_TMP/erl_nif.o" 2>/dev/null \
        | awk '/ T _enif_/ { sym = substr($3, 2); printf "extern void %s(void); __attribute__((used)) static void *_keep_%s = (void *)&%s;\n", sym, sym, sym }'
} > "$BUILD_DIR/enif_keepalive.c"
rm -rf "$NIF_O_TMP"
KEEP_COUNT=$(grep -c '^extern void enif_' "$BUILD_DIR/enif_keepalive.c" || true)
echo "  $KEEP_COUNT enif_* symbols pinned"
$CC -c "$BUILD_DIR/enif_keepalive.c" -o "$BUILD_DIR/enif_keepalive.o"

# ── Link ─────────────────────────────────────────────────────────────────────
echo "=== Linking $APP_NAME binary ==="
xcrun -sdk iphoneos swiftc \
    -target arm64-apple-ios17.0 \
    "$BUILD_DIR/driver_tab_ios.o" \
    "$BUILD_DIR/MobNode.o" \
    "$BUILD_DIR/swift_mob.o" \
    "$BUILD_DIR/mob_nif.o" \
    "$BUILD_DIR/mob_ble_nif.o" \
    "$BUILD_DIR/mob_beam.o" \
    "$BUILD_DIR/epmd_main.o" \
    "$BUILD_DIR/epmd_srv.o" \
    "$BUILD_DIR/epmd_cli.o" \
    "$BUILD_DIR/AppDelegate.o" \
    "$BUILD_DIR/beam_main.o" \
    "$BUILD_DIR/erl_errno_id_compat.o" \
    "$BUILD_DIR/enif_keepalive.o" \
    $LIBS \
    "$SQLITE_STATIC_LIB" \
    -lz -lc++ -lpthread \
    -Xlinker -dead_strip \
    -Xlinker -framework -Xlinker UIKit \
    -Xlinker -framework -Xlinker Foundation \
    -Xlinker -framework -Xlinker CoreGraphics \
    -Xlinker -framework -Xlinker QuartzCore \
    -Xlinker -framework -Xlinker SwiftUI \
    -Xlinker -framework -Xlinker CoreBluetooth \
    -Xlinker -framework -Xlinker CryptoKit \
    -o "$BUILD_DIR/$APP_NAME"

# ── Bundle ────────────────────────────────────────────────────────────────────
echo "=== Building .app bundle ==="
APP="$BUILD_DIR/$APP_NAME.app"
rm -rf "$APP"
mkdir -p "$APP"
cp "$BUILD_DIR/$APP_NAME" "$APP/"

# Patch bundle ID in Info.plist, then copy
cp ios/Info.plist "$APP/"
/usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "$APP/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleExecutable $APP_NAME"   "$APP/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME"         "$APP/Info.plist"

if [ -d "ios/Assets.xcassets/AppIcon.appiconset" ]; then
    ACTOOL_PLIST=$(mktemp /tmp/actool_XXXXXX.plist)
    xcrun actool ios/Assets.xcassets \
        --compile "$APP" --platform iphoneos \
        --minimum-deployment-target 17.0 \
        --app-icon AppIcon \
        --output-partial-info-plist "$ACTOOL_PLIST" 2>/dev/null || true
    /usr/libexec/PlistBuddy -c "Merge $ACTOOL_PLIST" "$APP/Info.plist" 2>/dev/null || true
    rm -f "$ACTOOL_PLIST"
fi

echo "=== Bundling OTP runtime inside .app ==="
OTP_BUNDLE="$APP/otp"
mkdir -p "$OTP_BUNDLE"
rsync -a --delete "$OTP_ROOT/lib/"      "$OTP_BUNDLE/lib/"
rsync -a --delete "$OTP_ROOT/releases/" "$OTP_BUNDLE/releases/"
rsync -a --delete "$OTP_ROOT/$APP_MODULE/" "$OTP_BUNDLE/$APP_MODULE/"
# Pythonx CPython bundle, copied alongside the OTP runtime so
# PythonxIosSpike.PythonPaths.detect/1 (or equivalent) finds it
# at <App>.app/otp/python/ via :code.root_dir/0.
[ -d "$OTP_ROOT/python" ] && rsync -a --delete "$OTP_ROOT/python/" "$OTP_BUNDLE/python/"
for f in "$OTP_ROOT"/*.png "$OTP_ROOT"/*.jpg; do
    [ -f "$f" ] && cp "$f" "$OTP_BUNDLE/"
done
mkdir -p "$OTP_BUNDLE/$ERTS_VSN/bin"
echo "  OTP bundle: $(du -sh "$OTP_BUNDLE" | cut -f1)"

# ── Slim build (default off for dev; opt in with `mix mob.deploy --slim`) ──
# Strip:
#   * disallowed binaries (.so/.a, standalone execs)  — Apple-policy parity
#   * unused OTP libs by prefix                       — bundle-size policy
#   * duplicate library versions                      — cache hygiene
#   * foreign apps from other projects                — cache hygiene
#   * src/ + include/ dirs                            — runtime doesn't need source
#   * .beam debug + doc chunks                        — runtime doesn't need debug info
# Same logic as MobDev.Release for the App Store path. Each step echoes a
# tagged size delta so a broken build can be traced to a specific step.
# Search the build log for `[SLIM:<step>]` to locate each pass.
if [ "${MOB_SLIM:-0}" = "1" ]; then
    slim_step() {
        local label=$1
        local before=$(du -sk "$OTP_BUNDLE" 2>/dev/null | awk '{print $1}')
        shift
        "$@"
        local after=$(du -sk "$OTP_BUNDLE" 2>/dev/null | awk '{print $1}')
        local delta=$((before - after))
        printf "[SLIM:%s] %s KB → %s KB  (-%s KB)\n" "$label" "$before" "$after" "$delta"
    }

    echo "=== Slim strip pass ==="

    slim_step apple_binaries bash -c '
        find "'"$OTP_BUNDLE"'" -type f \( -name "*.so" -o -name "*.a" \) -delete
        find "'"$OTP_BUNDLE"'" -path "*/priv/bin/*" -type f -delete
        find "'"$OTP_BUNDLE"'/'"$ERTS_VSN"'/bin" -type f -delete 2>/dev/null || true
    '

    slim_step prefix_libs bash -c '
        for prefix in megaco runtime_tools erl_interface os_mon wx et eunit \
                      observer debugger diameter edoc tools snmp dialyzer \
                      syntax_tools parsetools xmerl reltool inets ftp tftp \
                      common_test mnesia eldap odbc \
                      compiler ssh; do
            rm -rf "'"$OTP_BUNDLE"'/lib/$prefix-"*
        done
    '

    slim_step foreign_apps bash -c '
        for prefix in toy_ test_ mob_test scratch_; do
            rm -rf "'"$OTP_BUNDLE"'/lib/$prefix"*-*
        done
    '

    slim_step dedup_versions bash -c '
        set +e
        cd "'"$OTP_BUNDLE"'/lib"
        for name in $(ls -1 2>/dev/null | sed "s/-[0-9].*$//" | sort -u); do
            versions=$(ls -1d "${name}"-[0-9]* 2>/dev/null | sort -V)
            [ -z "$versions" ] && continue
            count=$(printf "%s\n" "$versions" | wc -l | tr -d " ")
            if [ "$count" -gt 1 ]; then
                latest=$(printf "%s\n" "$versions" | tail -1)
                for v in $versions; do
                    [ "$v" != "$latest" ] && rm -rf "$v"
                done
            fi
        done
    '

    slim_step src_and_headers find "$OTP_BUNDLE" -type d \( -name src -o -name include \) -prune -exec rm -rf {} +

    slim_step beam_chunks erl -noinput -boot start_clean -eval "
      case beam_lib:strip_release(\"$OTP_BUNDLE\") of
        {ok, _} -> erlang:halt(0);
        {error, beam_lib, R} ->
          io:format(standard_error, \"  strip_release error: ~p~n\", [R]),
          erlang:halt(1)
      end."

    echo "  Slim OTP bundle: $(du -sh "$OTP_BUNDLE" | cut -f1)"
else
    echo "[SLIM:skipped] MOB_SLIM=0 — keeping full OTP runtime"
fi

echo "=== Embedding provisioning profile ==="
PROFILE_DIR="$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles"
PROFILE="$PROFILE_DIR/${PROFILE_UUID}.mobileprovision"
if [ ! -f "$PROFILE" ]; then
    # Also check MobileDevice path (older Xcode versions)
    PROFILE="$HOME/Library/MobileDevice/Provisioning Profiles/${PROFILE_UUID}.mobileprovision"
fi
if [ ! -f "$PROFILE" ]; then
    echo "ERROR: Provisioning profile $PROFILE_UUID not found."
    echo "       Open Xcode → Settings → Accounts → Download Profiles"
    exit 1
fi
cp "$PROFILE" "$APP/embedded.mobileprovision"

echo "=== Code signing ==="
# Use project entitlements if present; otherwise generate from the profile.
ENTITLEMENTS_FILE=$(ls ios/*.entitlements 2>/dev/null | head -1 || true)
if [ -z "$ENTITLEMENTS_FILE" ]; then
    ENTITLEMENTS_FILE="$BUILD_DIR/mob_device.entitlements"
    # Mirror aps-environment from the profile so the binary entitlement
    # matches what the profile grants — without this, APNs registration
    # silently fails and the push token is never delivered.
    PROFILE_PLIST="$BUILD_DIR/embedded_profile.plist"
    security cms -D -i "$APP/embedded.mobileprovision" > "$PROFILE_PLIST" 2>/dev/null || true
    APS_ENV=$(/usr/libexec/PlistBuddy -c "Print :Entitlements:aps-environment" "$PROFILE_PLIST" 2>/dev/null || true)
    {
        printf '<?xml version="1.0" encoding="UTF-8"?>\n'
        printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        printf '<plist version="1.0">\n<dict>\n'
        printf '    <key>application-identifier</key>\n    <string>%s.%s</string>\n' "${TEAM_ID}" "${BUNDLE_ID}"
        printf '    <key>com.apple.developer.team-identifier</key>\n    <string>%s</string>\n' "${TEAM_ID}"
        printf '    <key>get-task-allow</key>\n    <true/>\n'
        [ -n "$APS_ENV" ] && printf '    <key>aps-environment</key>\n    <string>%s</string>\n' "${APS_ENV}"
        printf '</dict>\n</plist>\n'
    } > "$ENTITLEMENTS_FILE"
fi
# ── Codesign bundled Python dylibs (bottom-up: .so → framework → app) ──
# Apple's signing model is bottom-up: each Mach-O image inside the bundle
# must be signed with the same identity as the app, otherwise the iOS
# loader refuses to dlopen it on device. Skip when no Python bundle.
if [ -d "$OTP_BUNDLE/python" ]; then
    echo "=== Codesigning bundled Python dylibs ==="
    find "$OTP_BUNDLE/python/lib/python3.13/lib-dynload" -name "*.so" -print0 \
        | xargs -0 -I {} codesign --force --sign "$SIGN_IDENTITY" --timestamp=none {}
    echo "  signed $(find "$OTP_BUNDLE/python/lib/python3.13/lib-dynload" -name '*.so' | wc -l | tr -d ' ') lib-dynload extensions"

    codesign --force --sign "$SIGN_IDENTITY" --timestamp=none \
        "$OTP_BUNDLE/python/Python.framework/Python"
    echo "  signed Python.framework/Python"

    find "$OTP_BUNDLE/lib" -name 'libpythonx.so' -print0 \
        | xargs -0 -I {} codesign --force --sign "$SIGN_IDENTITY" --timestamp=none {}
    echo "  signed libpythonx.so"
fi

codesign --force --sign "$SIGN_IDENTITY" \
    --entitlements "$ENTITLEMENTS_FILE" \
    --timestamp=none \
    "$APP"

echo "=== Installing on device $DEVICE_UDID ==="
xcrun devicectl device install app --device "$DEVICE_UDID" "$APP"

echo "=== Build and install complete ==="
