// AppDelegate.m — Boots the Mob BEAM on a background thread and presents
// a SwiftUI root view via UIHostingController (created by MobUIFactory).

#import <UIKit/UIKit.h>
#import <pthread.h>
#include <stdlib.h>
#include "mob_beam.h"
#import "MobApp-Swift.h"  // generated by swiftc; exposes MobUIFactory

// Declared in mob_nif — delivers {:push_token, :ios, token} to the registered screen process.
extern void mob_send_push_token(const char* hex_token);

static void* beam_thread(void* arg) {
    mob_start_beam((const char*)arg);
    return NULL;
}

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)app
    didFinishLaunchingWithOptions:(NSDictionary*)opts {

    self.window = [[UIWindow alloc] initWithFrame:UIScreen.mainScreen.bounds];

    UIViewController* vc = [MobUIFactory makeRootViewController];
    self.window.rootViewController = vc;
    [self.window makeKeyAndVisible];

    mob_init_ui();

#ifdef DEBUG
    // Smoke-test bring-up: in DEBUG builds (mix mob.deploy --native),
    // auto-start the BLE self-test so the BLE scan + advertise loop
    // begins immediately. Release builds (mix mob.release) leave this
    // unset and behave normally. Mirrors the Android intent-extra path
    // (MainActivity.kt) so iOS can be exercised without a UI tap.
    //
    // NOTE: For this gate to actually fire on `mix mob.deploy --native`
    // builds, the build script must define DEBUG. As of this writing,
    // the Provision.xcodeproj Debug config does NOT set
    // GCC_PREPROCESSOR_DEFINITIONS=DEBUG=1, and the mob_dev
    // build_device.sh template does not either, so this branch is
    // currently never taken. Add `-DDEBUG=1` to the `$CC` flags in
    // native_build.ex's template (or to GCC_PREPROCESSOR_DEFINITIONS
    // in the Xcode project) to re-enable the autoselftest hook.
    setenv("MESHX_BLE_SELFTEST", "1", 1);
#endif

    extern const char* mob_app_module(void);
    pthread_t t;
    pthread_create(&t, NULL, beam_thread, (void*)mob_app_module());
    pthread_detach(t);

    return YES;
}

- (void)application:(UIApplication*)app
    didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken {
    // Convert token bytes to hex string and deliver to Elixir via NIF.
    NSMutableString* hex = [NSMutableString stringWithCapacity:deviceToken.length * 2];
    const unsigned char* bytes = (const unsigned char*)deviceToken.bytes;
    for (NSUInteger i = 0; i < deviceToken.length; i++) {
        [hex appendFormat:@"%02x", bytes[i]];
    }
    mob_send_push_token([hex UTF8String]);
}

- (void)application:(UIApplication*)app
    didFailToRegisterForRemoteNotificationsWithError:(NSError*)error {
    NSLog(@"[Mob] Failed to register for remote notifications: %@", error);
}

@end

int main(int argc, char* argv[]) {
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, @"AppDelegate");
    }
}
